// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedPanda.NLayered.Data.Sql;

#nullable disable

namespace RedPanda.NLayered.Data.Sql.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250917185608_Modify_MyMaps_AddTemperature")]
    partial class Modify_MyMaps_AddTemperature
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedPanda.NLayered.Domain.Map.MyMap", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<double?>("LastReportedTemperatureC")
                        .HasColumnType("float");

                    b.Property<string>("MapData")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id", "Date");

                    b.ToTable("MyMaps", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
